package mx.edu.inventario.ui;

import java.awt.*; import javax.swing.*; import javax.swing.table.DefaultTableModel; import mx.edu.inventario.exception.*; import mx.edu.inventario.model.Categoria; import mx.edu.inventario.service.InventarioService;

public class CategoriaDialog extends JDialog {
 private final InventarioService service; private final Runnable onChange; private final JTextField nombre=new JTextField(); private final JTextField descripcion=new JTextField(); private Integer id; private final DefaultTableModel model=new DefaultTableModel(new String[]{"ID","Nombre","Descripción"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable tabla=new JTable(model);
 public CategoriaDialog(Frame p,InventarioService s,Runnable r){super(p,"Categorías",true);service=s;onChange=r;setSize(600,400);setLocationRelativeTo(p);setLayout(new BorderLayout(7,7));JPanel f=new JPanel(new GridLayout(2,2,5,5));f.setBorder(BorderFactory.createTitledBorder("Datos de categoría"));f.add(new JLabel("Nombre"));f.add(nombre);f.add(new JLabel("Descripción"));f.add(descripcion);add(f,BorderLayout.NORTH);tabla.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting()&&tabla.getSelectedRow()>=0){int x=tabla.getSelectedRow();id=(Integer)model.getValueAt(x,0);nombre.setText((String)model.getValueAt(x,1));descripcion.setText((String)model.getValueAt(x,2));}});add(new JScrollPane(tabla),BorderLayout.CENTER);JPanel b=new JPanel();JButton n=new JButton("Nuevo"),g=new JButton("Guardar"),d=new JButton("Eliminar");n.addActionListener(e->limpiar());g.addActionListener(e->guardar());d.addActionListener(e->eliminar());b.add(n);b.add(g);b.add(d);add(b,BorderLayout.SOUTH);cargar();}
 private void cargar(){try{model.setRowCount(0);for(Categoria c:service.categorias())model.addRow(new Object[]{c.getId(),c.getNombre(),c.getDescripcion()});}catch(DataAccessException e){error(e.getMessage());}}
 private void guardar(){try{service.guardarCategoria(new Categoria(id,nombre.getText().trim(),descripcion.getText().trim()));limpiar();cargar();onChange.run();}catch(ValidationException|DataAccessException e){error(e.getMessage());}}
 private void eliminar(){if(id==null){error("Seleccione una categoría.");return;}try{service.eliminarCategoria(id);limpiar();cargar();onChange.run();}catch(DataAccessException e){error(e.getMessage());}}
 private void limpiar(){id=null;nombre.setText("");descripcion.setText("");tabla.clearSelection();} private void error(String x){JOptionPane.showMessageDialog(this,x,"Aviso",JOptionPane.ERROR_MESSAGE);}
}