package mx.edu.inventario.ui;

import java.awt.*; import java.awt.event.*; import java.util.List; import javax.swing.*; import javax.swing.table.DefaultTableModel;
import mx.edu.inventario.exception.*; import mx.edu.inventario.model.*; import mx.edu.inventario.service.InventarioService;

public class MainFrame extends JFrame {
    private final InventarioService service=new InventarioService(); private final JTextField txtNombre=new JTextField(); private final JTextField txtPrecio=new JTextField(); private final JTextField txtExistencia=new JTextField(); private final JTextField txtBuscar=new JTextField(); private final JComboBox<Categoria> cmbCategoria=new JComboBox<>();
    private final DefaultTableModel model=new DefaultTableModel(new String[]{"ID","Producto","Precio","Existencia","Categoría"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable tabla=new JTable(model); private Integer productoId;
    public MainFrame(){super("Sistema de Inventario");setDefaultCloseOperation(EXIT_ON_CLOSE);setSize(880,580);setLocationRelativeTo(null); construir(); cargar();}
    private void construir(){setLayout(new BorderLayout(10,10)); JPanel form=new JPanel(new GridLayout(2,5,8,5));form.setBorder(BorderFactory.createTitledBorder("Datos del producto")); form.add(new JLabel("Nombre"));form.add(new JLabel("Precio"));form.add(new JLabel("Existencia"));form.add(new JLabel("Categoría"));form.add(new JLabel(""));form.add(txtNombre);form.add(txtPrecio);form.add(txtExistencia);form.add(cmbCategoria);JButton categorias=new JButton("Gestionar categorías");categorias.addActionListener(e->abrirCategorias());form.add(categorias);add(form,BorderLayout.NORTH);
        JPanel center=new JPanel(new BorderLayout(5,5));JPanel search=new JPanel(new BorderLayout(5,5));search.add(new JLabel("Buscar:"),BorderLayout.WEST);search.add(txtBuscar);JButton buscar=new JButton("Filtrar");buscar.addActionListener(e->cargarProductos());search.add(buscar,BorderLayout.EAST);center.add(search,BorderLayout.NORTH);tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);tabla.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting())seleccionar();});center.add(new JScrollPane(tabla),BorderLayout.CENTER);add(center,BorderLayout.CENTER);
        JPanel buttons=new JPanel(); for(String s:new String[]{"Nuevo","Guardar","Eliminar","Actualizar"}){JButton b=new JButton(s);buttons.add(b);if(s.equals("Nuevo"))b.addActionListener(e->limpiar());if(s.equals("Guardar")||s.equals("Actualizar"))b.addActionListener(e->guardar());if(s.equals("Eliminar"))b.addActionListener(e->eliminar());}add(buttons,BorderLayout.SOUTH);}
    private void cargar(){try{cargarCategorias();cargarProductos();}catch(DataAccessException e){error(e.getMessage());}}
    private void cargarCategorias()throws DataAccessException{cmbCategoria.removeAllItems();for(Categoria c:service.categorias())cmbCategoria.addItem(c);}
    private void cargarProductos(){try{model.setRowCount(0);for(Producto p:service.productos(txtBuscar.getText()))model.addRow(new Object[]{p.getId(),p.getNombre(),String.format("$ %.2f",p.getPrecio()),p.getExistencia(),p.getCategoria().getNombre()});}catch(DataAccessException e){error(e.getMessage());}}
    private void seleccionar(){int r=tabla.getSelectedRow();if(r<0)return;productoId=(Integer)model.getValueAt(r,0);txtNombre.setText((String)model.getValueAt(r,1));txtPrecio.setText(model.getValueAt(r,2).toString().replace("$ ",""));txtExistencia.setText(model.getValueAt(r,3).toString());String cat=model.getValueAt(r,4).toString();for(int i=0;i<cmbCategoria.getItemCount();i++)if(cmbCategoria.getItemAt(i).getNombre().equals(cat))cmbCategoria.setSelectedIndex(i);}
    private void guardar(){try{Producto p=new Producto(productoId,txtNombre.getText().trim(),Double.parseDouble(txtPrecio.getText().trim()),Integer.parseInt(txtExistencia.getText().trim()),(Categoria)cmbCategoria.getSelectedItem());service.guardarProducto(p);limpiar();cargarProductos();}catch(NumberFormatException e){error("Precio y existencia deben ser valores numéricos válidos.");}catch(ValidationException|DataAccessException e){error(e.getMessage());}}
    private void eliminar(){if(productoId==null){error("Seleccione un producto para eliminar.");return;}if(JOptionPane.showConfirmDialog(this,"¿Eliminar el producto seleccionado?","Confirmar",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)try{service.eliminarProducto(productoId);limpiar();cargarProductos();}catch(DataAccessException e){error(e.getMessage());}}
    private void limpiar(){productoId=null;txtNombre.setText("");txtPrecio.setText("");txtExistencia.setText("");tabla.clearSelection();txtNombre.requestFocus();}
    private void abrirCategorias(){new CategoriaDialog(this,service,()->{try{cargarCategorias();}catch(DataAccessException e){error(e.getMessage());}}).setVisible(true);}
    private void error(String m){JOptionPane.showMessageDialog(this,m,"Aviso",JOptionPane.ERROR_MESSAGE);}
}